Add the dependency to the http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/Grails[Spring Security Rest for Grails plugin].

[source,groovy]
./build.gradle
----
include::{sourceDir}/build.gradle[indent=0,lines=56]
----

We run _s2-quickstart_ command, provided by the  https://grails-plugins.github.io/grails-spring-security-core/v3/index.html[Spring Security Core Plugin],
to generate User and Authority classes.

[source,bash]
----
./grailsw s2-quickstart grails.test.security User SecurityRole
----

We have configured every security detail of the application in the file _application.groovy_.
We have one http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_plugin_configuration[stateless chain and one Traditional Chain].

[source,groovy]
.grails-app/conf/application.groovy
----
include::{sourceDir}/grails-app/conf/application.groovy[indent=0]
----

<1> We choose to configure security with a https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#configGroovyMap[InterceptUrlMap]
<2> Stateless Chain
<3> Traditional chain
<4> Classes generated by the s2-quickstart script
<5> https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#urlProperties[URL of login page]
<6> Url accesible only for users authenticated and with role ROLE_BOSS or ROLE_EMPLOYEE
<7> Spring Security Rest for Grails default Authentication Endpoint. It should allow anonymous access
<8> Spring Security Rest for Grails default Refresh Token Endpoint. It should allow anonymous access
<9> Url accesible only for users authenticated and with role ROLE_BOSS
[source,groovy]

We populate the app with two users when the application starts.

.grails-app/init/grails/test/security/BootStrap.groovy
----
include::{sourceDir}/grails-app/init/grails/test/security/BootStrap.groovy[indent=0]
----
