Add a dependency on the http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/[Grails Spring Security Rest plugin]
and to the latest release of https://grails-plugins.github.io/grails-spring-security-core/v3/index.html[Spring Security Core]
to our `build.gradle` file.

[source,groovy]
./build.gradle
----
include::{sourceDir}/build.gradle[tags=dependencySSR]
----

We'll run the _s2-quickstart_ command, provided by the  https://grails-plugins.github.io/grails-spring-security-core/v3/index.html[Spring Security Core Plugin],
to generate `User` and `Authority` classes.

[source,bash]
----
./grailsw s2-quickstart grails.test.security User SecurityRole
----

`s2-quickstart` script generates three domain classes; `User`, `SecurityRole` and `UserSecurityRole`.

[source,groovy]
.grails-app/domain/grails/test/security/User.groovy
----
include::{sourceDir}/grails-app/domain/grails/test/security/User.groovy[indent=0]
----

[source,groovy]
.grails-app/domain/grails/test/security/SecurityRole.groovy
----
include::{sourceDir}/grails-app/domain/grails/test/security/SecurityRole.groovy[indent=0]
----

[source,groovy]
.grails-app/domain/grails/test/security/UserSecurityRole.groovy
----
include::{sourceDir}/grails-app/domain/grails/test/security/UserSecurityRole.groovy[indent=0]
----

If you are using GORM 6.0.10 or a later version and Spring Security core 3.1.2 or later version, s2-quickstart
generates and registers a bean to handle password encoding:

[source,groovy]
.src/main/groovy/grails/test/security/UserPasswordEncoderListener.groovy
----
include::{sourceDir}/src/main/groovy/grails/test/security/UserPasswordEncoderListener.groovy[indent=0]
----

[source,groovy]
.grails-app/conf/spring/resources.groovy
----
include::{sourceDir}/grails-app/conf/spring/resources.groovy[indent=0]
----

We'll configure the security rules of the application in the file _application.groovy_, as show below. We have one http://alvarosanchez.github.io/grails-spring-security-rest/latest/docs/#_plugin_configuration[stateless chain and one Traditional Chain].

[source,groovy]
.grails-app/conf/application.groovy
----
include::{sourceDir}/grails-app/conf/application.groovy[indent=0]
----

<1> We choose to configure security with a https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#configGroovyMap[InterceptUrlMap]
<2> Stateless Chain
<3> Traditional chain
<4> Classes generated by the s2-quickstart script
<5> https://grails-plugins.github.io/grails-spring-security-core/v3/index.html#urlProperties[URL of login page]
<6> Url accesible only for users authenticated and with role ROLE_BOSS or ROLE_EMPLOYEE
<7> Spring Security Rest for Grails default Authentication Endpoint. It should allow anonymous access
<8> Spring Security Rest for Grails default Refresh Token Endpoint. It should allow anonymous access
<9> Url accesible only for users authenticated and with role ROLE_BOSS
[source,groovy]

We'll populate our database in `BootStrap`, inserting two users when the application starts.

.grails-app/init/grails/test/security/BootStrap.groovy
----
include::{sourceDir}/grails-app/init/grails/test/security/BootStrap.groovy[indent=0]
----
