To test REST part of the application, we use https://github.com/grails-plugins/grails-rest-client-builder[Rest Client Builder Grails Plugin]. We need to add the dependency: 

[source,groovy]
./build.gradle
----
include::{sourceDir}/build.gradle[tags=dependencyRestClient]
----

Our first test will verify that the _/api/announcements_ endpoint is only accessible to users with role _ROLE_BOSS_

[source,groovy]
./src/integration-test/groovy/example/grails/ApiAnnouncementControllerSpec.groovy
----
include::{sourceDir}/src/integration-test/groovy/example/grails/ApiAnnouncementControllerSpec.groovy[indent=0]
----

<1> _serverPort_ property is automatically injected and it contains the random port where the app will be running for the functional test.
<2> If you want JSON in the response, you should configure the _Accept_ header to indicate you expect a JSON response.
<3> When you are submitting a JSON payload in the request body, you should set the _Content-Type_ header appropriately.
<4> The server returns a 401, indicating that the resource is secured.
<5> Call the authentication endpoint
<6> We pass the _access_token_ we obtained from the authentication endpoint in the request headers.
<7> An authenticated user with the role `ROLE_BOSS` can access the resource.
<8> An authenticated user but without the role `ROLE_BOSS` is not allowed to access the resource.
